# Generated by Django 3.1.7 on 2021-04-01 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favoriteslist',
            options={'default_related_name': 'favorites_lists'},
        ),
        migrations.AddField(
            model_name='favoriteslist',
            name='link',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='favoriteslist',
            name='title',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
